version: "3"
services:
  api:
    container_name: api
    build: ./server
    environment:
      - SECRET_WORD=${SECRET_WORD}
    depends_on:
      - mongo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./server:/usr/src/
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  web:
    container_name: web
    build:
      context: ./web-app
    environment:
      - SECRET_WORD=${SECRET_WORD}
    depends_on:
      - api
    ports:
      - "4200:4200"
    links:
      - api

# sudo docker-compose build
# sudo docker-compose up -d
